[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation",
    "src/starter"
]
resolver = "2"

[workspace.dependencies]
actix-web = "4.9.0"

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

uuid = { version = "1.11.0", features = ["v4", "serde"] }
readonly = "0.2.12"
tokio-postgres = { version = "0.7.12", features = ["with-uuid-1"] }
postgres-types = { version = "0.2.8", features = ["uuid-1"] }
refinery = { version = "0.8.14", features = ["tokio-postgres"] }
tokio = { version = "1.41.0", features = ["full"] }
async-trait = "0.1.83"
deadpool-postgres = { version = "0.14.0", features = ["serde"] }
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
serial_test = "3.1.1"

# Logging
log = "0.4.22"
pretty_env_logger = "0.5.0"
env_logger = "0.11.5"

# Configuration
dotenv = "0.15.0"
config = "0.14.1"

# Error Handling
anyhow = "1.0.92"
thiserror = "1.0.68"

# Testing
testcontainers = "0.23.1"
testcontainers-modules = { version = "0.11.3", features = ["postgres"] }
reqwest = { version = "0.12.9", features = ["json"]}

# Misc
once_cell = "1.20.2"
ctor = "0.2.8"
async-std = { version = "1", features = ["attributes", "tokio1"] }
