[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation",
    "src/starter"
]

[workspace.dependencies]
actix-web = "4.3"
log = "0.4"
confy = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
uuid = { verson = "1.3", features = ["v4", "serde"] }
readonly = "0.2"
