[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation",
    "src/starter"
]

[workspace.dependencies]
actix-web = "4.3"
log = "0.4"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
uuid = { verson = "1.3", features = ["v4", "serde"] }
readonly = "0.2"
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
postgres-types = { version = "0.2", features = ["uuid-1"] }
refinery = { version = "0.8", features = ["tokio-postgres"] }
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1"
deadpool-postgres = { version = "0.10", features = ["serde"] }
