[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation",
    "src/starter"
]
resolver = "2"

[workspace.dependencies]

# Web
actix-web = "4.9.0"

# OpenAPI
utoipa = { version = "5.3.1", features = ["actix_extras", "uuid"] }
utoipa-actix-web = "0.1.2"
utoipa-swagger-ui = { version = "8.1.1", features = ["actix-web"] }

# Serialization
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"

# Async
tokio = { version = "1.43.0", features = ["full"] }
async-trait = "0.1.86"

# Database and ORM
tokio-postgres = { version = "0.7.13", features = ["with-uuid-1"] }
diesel = { version = "2.2.7", features = ["postgres", "r2d2", "uuid"] }
diesel_migrations = "2.0.0"

# Logging
log = "0.4.26"
env_logger = "0.11.6"

# Configuration
dotenv = "0.15.0"
config = "0.15.8"

# Error Handling
anyhow = "1.0.97"
thiserror = "2.0.12"

# Testing
testcontainers = "0.23.3"
testcontainers-modules = { version = "0.11.6", features = ["postgres"] }
reqwest = { version = "0.12.11", features = ["json"]}
serial_test = "3.2.0"

# Misc
ctor = "0.2.9"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
readonly = "0.2.12"
