[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation",
    "src/starter"
]

[workspace.dependencies]
actix-web = "4.3"
log = "0.4"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"
uuid = { verson = "1.3", features = ["v4", "serde"] }
readonly = "0.2"
tokio-postgres = "0.7"
refinery = { version = "0.8", features = ["tokio-postgres"]}
tokio = { version = "1.9", features = ["full"] }
