[workspace]
members = [
    "src/domain",
    "src/infrastructure",
    "src/application",
    "src/presentation"
]

[package]
name = "rust-microservice-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
confy = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.10.0"
