ALTER TABLE to_do_items
ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ NULL;

DROP TRIGGER IF EXISTS set_updated_at ON to_do_items;
SELECT diesel_manage_updated_at('to_do_items');
