volumes:
  postgres-rust:

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "0.0.0.0:5432:5432"
    networks:
      - rust-dev-network
    volumes:
      - postgres-rust:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=postgres pg_isready -U postgres -h postgres"]
      interval: 10s
      timeout: 30s
      retries: 15

networks:
  rust-dev-network:
