[package]
name = "starter"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
serde.workspace = true
env_logger.workspace = true
actix-web.workspace = true
config.workspace = true
readonly.workspace = true
deadpool-postgres.workspace = true
tokio.workspace = true
anyhow.workspace = true
reqwest.workspace = true

domain = { path = "../domain" }
application = { path = "../application" }
presentation = { path = "../presentation" }
infrastructure = { path = "../infrastructure" }
once_cell = "1.19.0"
uuid = { version = "1.10.0", features = ["v4"] }

[dev-dependencies]
testcontainers.workspace = true
testcontainers-modules.workspace = true
ctor.workspace = true
async-std.workspace = true
serial_test.workspace = true

