name: build-by-tag

on:
  push:
    tags:
    - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Cache
      uses: actions/cache@v4
      with:
          path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: stable
    - name: Build
      run: cargo build --release --all-features
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/nkz-soft/rust-microservice-template/rust-microservice-template
    - name: Login to Github Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build image and push to GitHub Container Registry
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
